#!/usr/bin/python3

import json
import nav
import git
from shell import get_cmd

def summarise(repos_dir):
    repos = []
    for repo in nav.explore_repos(repos_dir):
        git_info = {
            'name': repo,
            'is_clean': git.is_clean(),
            'current_branch': git.get_branch(),
            'remotes': git.get_remotes()
        }
        repos.append(git_info)
    return repos

usage_instructions = '''
    Usage: ./sirup sum --repos ./path/to/repos
'''.strip()

if __name__ == '__main__':
    cmd, success = get_cmd()
    if not success:
        print(usage_instructions)
        exit(1)

    if cmd['name'] == 'sum':
        repos_path = cmd['args']['--repos']
        summary = summarise(repos_path)
        json_output = json.dumps(summary)
        print(json_output)
        exit(0)

    print('This command is not yet implemented')
